"Name: \PR:SAPLFACG\FO:SET_XMFRW\SE:BEGIN\EI
ENHANCEMENT 0 ZENH_BSEG_VBUND.
    DATA: WA_CD_SOC_GL LIKE ZFI_CD_SOC_GL.
    DATA: WA_KNA1 LIKE KNA1.
    DATA: WA_LFA1 LIKE LFA1.
    DATA: V_VBUND TYPE RASSC.

    CLEAR V_VBUND.

    IF SY-TCODE EQ 'FB01'.
      READ TABLE T_BKPF INDEX 1.
      SELECT SINGLE * FROM ZFI_CD_SOC_GL INTO WA_CD_SOC_GL WHERE BLART EQ T_BKPF-BLART.
      IF SY-SUBRC EQ 0.
        LOOP AT T_BSEG.
          IF T_BSEG-KUNNR IS NOT INITIAL.
            SELECT SINGLE * FROM KNA1 INTO WA_KNA1 WHERE KUNNR EQ T_BSEG-KUNNR.
            IF SY-SUBRC EQ 0.
              IF WA_KNA1-VBUND IS NOT INITIAL.
                MOVE WA_KNA1-VBUND TO V_VBUND.
                EXIT.
              ENDIF.
            ENDIF.
          ENDIF.
          IF T_BSEG-LIFNR IS NOT INITIAL.
            SELECT SINGLE * FROM LFA1 INTO WA_LFA1 WHERE LIFNR EQ T_BSEG-LIFNR.
            IF SY-SUBRC EQ 0.
              IF WA_LFA1-VBUND IS NOT INITIAL.
                MOVE WA_LFA1-VBUND TO V_VBUND.
                EXIT.
              ENDIF.
            ENDIF.
          ENDIF.
        ENDLOOP.
        IF V_VBUND IS NOT INITIAL.
          LOOP AT T_BSEG.
            MOVE V_VBUND TO T_BSEG-VBUND.
            MODIFY T_BSEG.
          ENDLOOP.
        ENDIF.
      ENDIF.


      DATA: IT_ZSGL_CUENTAS TYPE STANDARD TABLE OF ZSGL_CUENTAS,
            WA_ZSGL_CUENTAS TYPE ZSGL_CUENTAS,
            VL_FLAG         TYPE ABAP_BOOL.

      SELECT * FROM ZSGL_CUENTAS
        INTO TABLE IT_ZSGL_CUENTAS.
      IF IT_ZSGL_CUENTAS[] IS NOT INITIAL.
        LOOP AT T_BSEG.
          LOOP AT IT_ZSGL_CUENTAS INTO WA_ZSGL_CUENTAS.
            IF WA_ZSGL_CUENTAS-SAKNR_FROM IS NOT INITIAL AND WA_ZSGL_CUENTAS-SAKNR_TO IS NOT INITIAL.
              IF T_BSEG-HKONT BETWEEN WA_ZSGL_CUENTAS-SAKNR_FROM AND WA_ZSGL_CUENTAS-SAKNR_TO.
                MOVE ABAP_FALSE TO VL_FLAG.
                EXIT.
              ENDIF.
              MOVE ABAP_TRUE TO VL_FLAG.
            ELSEIF WA_ZSGL_CUENTAS-SAKNR_FROM IS NOT INITIAL AND WA_ZSGL_CUENTAS-SAKNR_TO IS INITIAL.
              IF T_BSEG-HKONT EQ WA_ZSGL_CUENTAS-SAKNR_FROM.
                MOVE ABAP_FALSE TO VL_FLAG.
                EXIT.
              ENDIF.
              MOVE ABAP_TRUE TO VL_FLAG.
            ENDIF.


            IF WA_ZSGL_CUENTAS-LIFNR_FROM IS NOT INITIAL AND WA_ZSGL_CUENTAS-LIFNR_TO IS NOT INITIAL.
              IF T_BSEG-LIFNR BETWEEN WA_ZSGL_CUENTAS-LIFNR_FROM AND WA_ZSGL_CUENTAS-LIFNR_TO.
                MOVE ABAP_FALSE TO VL_FLAG.
                EXIT.
              ENDIF.
              MOVE ABAP_TRUE TO VL_FLAG.
            ELSEIF WA_ZSGL_CUENTAS-LIFNR_FROM IS NOT INITIAL AND WA_ZSGL_CUENTAS-LIFNR_TO IS INITIAL.
              IF T_BSEG-LIFNR EQ WA_ZSGL_CUENTAS-LIFNR_FROM.
                MOVE ABAP_FALSE TO VL_FLAG.
                EXIT.
              ENDIF.
              MOVE ABAP_TRUE TO VL_FLAG.
            ENDIF.


            IF WA_ZSGL_CUENTAS-KUNNR_FROM IS NOT INITIAL AND WA_ZSGL_CUENTAS-KUNNR_TO IS NOT INITIAL.
              IF T_BSEG-KUNNR BETWEEN WA_ZSGL_CUENTAS-KUNNR_FROM AND WA_ZSGL_CUENTAS-KUNNR_TO.
                MOVE ABAP_FALSE TO VL_FLAG.
                EXIT.
              ENDIF.
              MOVE ABAP_TRUE TO VL_FLAG.
            ELSEIF WA_ZSGL_CUENTAS-KUNNR_FROM IS NOT INITIAL AND WA_ZSGL_CUENTAS-KUNNR_TO IS INITIAL.
              IF T_BSEG-KUNNR EQ WA_ZSGL_CUENTAS-KUNNR_FROM.
                MOVE ABAP_FALSE TO VL_FLAG.
                EXIT.
              ENDIF.
              MOVE ABAP_TRUE TO VL_FLAG.
            ENDIF.

          ENDLOOP.
          IF VL_FLAG EQ ABAP_FALSE.
            MOVE SPACE TO T_BSEG-VBUND.
          ELSEIF VL_FLAG EQ ABAP_TRUE.
            MOVE V_VBUND TO T_BSEG-VBUND.
          ENDIF.
          MODIFY T_BSEG.
        ENDLOOP.
      ENDIF.

    ENDIF.
ENDENHANCEMENT.
