"Name: \PR:SAPLAIST\FO:UPDATE_PREPARE\SE:END\EI
ENHANCEMENT 0 ZENH_ACTFIJO.
*
   DATA: V_BAND TYPE C LENGTH 1.
   IF SY-TCODE EQ 'AS01' OR SY-TCODE EQ 'AS02' OR SY-TCODE EQ 'AS03'.
    IF SY-TCODE EQ 'AS02' OR SY-TCODE EQ 'AS03'.
        IF V_ANS EQ '2' OR V_ANS EQ 'A'.
           V_BAND = 'X'.
        ENDIF.
    ENDIF.

    IF V_BAND EQ ''.
     IF anla-anln1 IS NOT INITIAL.
       LOOP AT IT_FIELD INTO WA_FIELD.
         IF WA_FIELD-FIELDNAME EQ 'CVSAT'.
          WA_DMAF-CVSAT = WA_FIELD-VALUE.
         ELSEIF WA_FIELD-FIELDNAME = 'CVUNI'.
          WA_DMAF-CVUNI = WA_FIELD-VALUE.
         ELSEIF WA_FIELD-FIELDNAME = 'DESUN'.
          WA_DMAF-DESUN = WA_FIELD-VALUE.
         ELSEIF WA_FIELD-FIELDNAME = 'UCFDI'.
          WA_DMAF-UCFDI = WA_FIELD-VALUE.
         ENDIF.
       ENDLOOP.

        WA_DMAF-BUKRS = anla-BUKRS.
        WA_DMAF-ANLKL = anla-ANLKL.
        WA_DMAF-GJAHR = anla-ERDAT(4).
        WA_DMAF-ANLN1 = anla-ANLN1.

        MODIFY ZCFDITT_DMAF FROM WA_DMAF.

      ENDIF.
    ENDIF.
  ENDIF.



ENDENHANCEMENT.
