"Name: \PR:RFITEMGL\FO:SEL_ACCOUNT_CHECK\SE:BEGIN\EI
ENHANCEMENT 0 ZFIENH_MONITODEPOSITOS.
*
  FREE MEMORY ID 'IT_MONITORDEPOSITOS'.
  EXPORT IT_POS TO MEMORY ID 'IT_MONITORDEPOSITOS'.

ENDENHANCEMENT.
