"Name: \PR:SAPLF02L\FO:KNKK_BEARBEITEN\SE:END\EI
ENHANCEMENT 0 ZFIENH007_SAVI.
*
  IF SY-TCODE EQ 'FD32'.
    DATA V_RES TYPE STRING.
    IF KNKK-GRUPP EQ 'SAVI'.
    CALL FUNCTION 'ZCCFIMF007_CREDITOSAVI'
    EXPORTING
       P_DEUDOR = KNKK-KUNNR
       P_LIM_CR = KNKK-KLIMK
       P_KKBER = KNKK-KKBER
    IMPORTING
       V_MESSAGE = V_RES.
    ENDIF.
  ENDIF.

ENDENHANCEMENT.
